- .eslintignore
- .eslintrc.json
- .prettierignore
- .prettierrc.json
- .vscode/settings.json
- package.json
- src/App.tsx
- src/components/BackButton/index.tsx
- src/components/ConnectButton/index.tsx
- src/components/Form/FormInput.tsx
- src/components/Form/FormInputLabel.tsx
- src/components/Form/index.tsx
- src/components/PageHeader/index.tsx
- src/const/market.const.ts
- src/context/web3ProviderContext.ts
- src/main.tsx
- src/pages/growth/index.tsx
- src/pages/home/HomeNavitem.tsx
- src/pages/home/index.tsx
- src/pages/tokenize-invitation/index.tsx
- src/pages/tokenize-market-select/TokenizeLink.tsx
- src/pages/tokenize-market-select/index.tsx
- src/pages/tokens/UserTokenListItem.tsx
- src/pages/tokens/index.tsx
- src/types/userToken.ts
- src/utils/utils.ts
- yarn.lock
> adds linting for vite

- package.json
- src/utils/utils.test.ts
- yarn.lock
> vitest added

- src/components/BackButton/index.tsx
- src/components/Form/index.tsx
- src/context/tokenizeContext.tsx
- src/pages/tokenize-form/GithubForm.tsx
- src/pages/tokenize-form/index.tsx
- src/pages/tokenize-submit-preview/index.tsx
> tokenize submit UI

- package.json
- src/App.tsx
- src/context/tokenizeContext.tsx
- src/pages/token/index.tsx
- src/pages/tokenize-form/GithubForm.tsx
- src/pages/tokenize-submit/index.tsx
- src/pages/tokenize-submit/tokenize-submit.hooks.ts
- src/utils/utils.ts
- yarn.lock
> Tokenize submit

- src/hooks/useMetrics.ts
- src/pages/tokenize-form/GithubForm.tsx
- src/pages/tokenize-submit/tokenize-submit.hooks.ts
- yarn.lock
Checks metrics before tokenizing.
In short...
```ts
const market = createMarketContract(provider)(someMarketAddress)
const behavior = await market.behavior()
const marketBehavior = createMarketBehaviorContract(provider)(behavior)
const metricsAddress = await marketBehavior.getMetrics({id})// for example github repo name or youtube channel id
if (metricsAddress === '0x0000000000000000000000000000000000000000') {
await createAndAuthenticate()
}
```
> check metrics before tokenizing

- src/components/ConnectButton/index.tsx
- src/components/HSButton/index.tsx
- Fixes bug when user changes account, UI isn't updated
- Fixes UI Hashi Button bug where internal url changes should use <Link> instead of <a> 
closes #70
> on account change bugfix

- src/hooks/usePositionsOfOwner.ts
- src/pages/stake/index.tsx
- src/utils/utils.ts
Gets user position of new stake for stakes.social link
> Filter new stake position

- src/App.tsx
> adds correct urls for footer links

- README.md
- package.json
- src/App.tsx
- src/env.d.ts
- src/hooks/useApprove.ts
- src/pages/stake/index.tsx
- src/pages/stake/useLockup.ts
- src/pages/user-positions-list/UserPositionListItem.tsx
- src/pages/user-positions-list/index.tsx
- src/types/Position.ts
- yarn.lock
- Updates to most recent dev-kit-js
- Uses dev-kit Positions type, removes manually coded one
- Removes "Approve" in staking, due to updates to `positionsCreate`
> updates dev-kit; removes "approve" step from staking

- TERMS-OF-SERVICE.md
- Adds terms and conditions markdown
> terms and conditions

- src/components/CheckBox/index.tsx
- src/context/tokenizeContext.tsx
- src/pages/tokenize-form/GithubForm.tsx
- src/pages/tokenize-form/TermsCheckBox.tsx
- src/pages/tokenize-form/YouTubeForm.tsx
adds checkbox for terms on tokenize-form
> terms guard for property tokenization

- src/components/DPLTitleBar/index.tsx
- src/components/HomeNavItem/index.tsx
- src/pages/property/StakeOption.tsx
- src/pages/tokenize-form/GithubForm.tsx
- src/pages/tokenize-form/TermsCheckBox.tsx
- src/pages/tokenize-submit/index.tsx
- tailwind.config.js
> link color and gradient stops

- src/components/BackButton/index.tsx
- src/components/Card/index.tsx
- src/components/ConnectButton/index.tsx
- src/components/DPLFooter/index.tsx
- src/components/DPLHeader/index.tsx
- src/components/DPLTitleBar/index.tsx
- src/components/Form/index.tsx
- src/components/HSTextField/index.tsx
- src/components/HomeNavItem/index.tsx
- src/pages/home/index.tsx
- src/pages/property/StakeOption.tsx
- src/pages/property/index.tsx
- src/pages/tokenize-form/GithubForm.tsx
- src/pages/tokenize-form/TermsCheckBox.tsx
- src/pages/tokenize-form/YouTubeForm.tsx
- src/pages/tokenize-market-select/index.tsx
- src/pages/tokenize-submit/index.tsx
- src/pages/user-properties-list/index.tsx
- tailwind.config.js
> space theming

- src/components/ConnectButton/index.tsx
- src/components/DPLTitleBar/index.tsx
- src/components/HowItWorks/FaqCard.tsx
- src/components/HowItWorks/StepsCard.tsx
- src/components/HowItWorks/index.tsx
- src/components/TitleSubSection/index.tsx
- src/pages/property/index.tsx
- src/pages/stake/index.tsx
- src/pages/tokenize-form/index.tsx
- src/pages/tokenize-market-select/index.tsx
- src/pages/tokenize-submit/index.tsx
- src/pages/user-positions-list/index.tsx
- src/pages/user-properties-list/index.tsx
- src/utils/utils.ts
- How it works styling
- Property Page styling
- Explorer URL util
- Small Title Bar rewrite
> How it works styling

- src/components/HowItWorks/index.tsx
- src/pages/stake/index.tsx
- Connect wallet section styling
- Add section divider between How It Works
> Connect Wallet Section Styling

- src/components/DPLHeader/index.tsx
- src/components/HSButton/index.tsx
- src/pages/stake/StakeStep.tsx
- src/pages/stake/index.tsx
- tailwind.config.js
- Adds back in "Approve" to stake steps
- Basic Stake Step component styling
- Tailwind "success" color theming
> Stake steps

- src/components/DPLTitleBar/index.tsx
- src/components/NavTabs/index.tsx
- src/pages/property/index.tsx
- src/pages/stake/index.tsx
- src/pages/tokenize-form/index.tsx
- src/pages/tokenize-market-select/index.tsx
- src/pages/tokenize-submit/index.tsx
- src/pages/user-positions-list/index.tsx
- src/pages/user-properties-list/index.tsx
- Simple Tabs added to user address section
- renames TitleBar `classNames` to `className` for consistency
> user address nav pills added

- src/pages/user-positions-list/UserPositionListItem.tsx
- src/pages/user-positions-list/index.tsx
Style the User Position Items
Items styled in `UserPositionListItem` component
> positions styled

- src/App.tsx
- src/const/index.ts
Update deployment urls for beta launch
- Updates the DEPLOYMENTS const
- Uses DEPLOYMENTS const in footer
closes #68
> updates deployment links for beta launch

- src/components/ConnectButton/index.tsx
- src/components/DPLHeader/index.tsx
Break down header for mobile
Tailwind breakpoints added in ConnectButton and Header
> header mobile breakpoints added

- PRIVACY-POLICY.md
- src/App.tsx
Add Privacy Policy
Adds PRIVACY-POLICY.md and a link in the footer
> adds privacy policy

- src/App.tsx
- src/components/DPLFooter/index.tsx
- src/components/HowItWorks/StepsCard.tsx
- src/components/HowItWorks/index.tsx
- src/pages/tokenize-market-select/TokenizeLink.tsx
- src/pages/tokenize-market-select/index.tsx
- src/utils/utils.ts
- Add major DEXs link to "How it works"
- Add GitHub and Discord link to footer
- Add the forum link to the market suggestion
> Add some links

- src/components/Tweet/index.tsx
- src/pages/property/index.tsx
- src/pages/stake/index.tsx
> Add tweet link

- src/components/ConnectButton/index.tsx
- src/pages/tokenize-form/YouTubeForm.tsx
- src/utils/utils.test.ts
- src/utils/utils.ts
Add some tests to ensure util safety
- Cleanup utils and removes some unused functions
- Adds more tests in utils.test.ts
> Util testing

- src/App.tsx
- src/pages/tokenize-form/index.tsx
- src/pages/tokenize-market-select/index.tsx
- src/pages/wait-market/index.tsx
Redirect YouTube tokenization to "wait" page with Discord link 
- Adds WaitMarketPage component
- New route added
- When Tokenize->Market Select->YouTube selected, route to wait page
> youtube coming soon page

- src/pages/network-select/index.tsx
> fix the host

- index.html
Update title from Launcher to Niwa
Updates title from Launcher to Niwa
> updates title to Niwa

- PRIVACY-POLICY.md
- package.json
- src/App.tsx
- src/components/Footer/index.tsx
- src/pages/markdown-page/MarkdownPage.module.scss
- src/pages/markdown-page/index.tsx
- src/vite.d.ts
- vite.config.ts
- yarn.lock
Add a page for Markdown rendering so we can host Privacy Policy and Terms and Conditions page
- Creates a MarkdownPage
- Config for Vite MD
- Moves Footer inside of BrowserRouter so we can use <Link> instead of <a>
> adds markdown page for privacy policy and terms and conditions

- src/App.tsx
Privacy Policy + Terms and Conditions routes need to be added to root app
Routes updates
> markdown routes added to root

- src/pages/auth-callback/index.tsx
- src/pages/stake/index.tsx
- src/pages/tokenize-form/YouTubeForm.tsx
- src/pages/tokenize-form/index.tsx
- src/pages/tokenize-market-select/index.tsx
- src/pages/tokenize-submit/TokenizePreviewSubmit.tsx
- src/pages/tokenize-submit/index.tsx
change procedure:
- Auth YouTube Account on `/tokenize/youtube` 
- get channleId, accessToken, and store context, navigate to `/tokenize/youtube` 
- inputs token symbol + token name
- Click Preview button, and navigate to `/tokenize/youtube/preview`
- integrate Khaos
> Reform youtube market

- src/hooks/usePropertyDetails.ts
- src/pages/property/index.tsx
Fixes bug on Property YouTube page, displaying incorrect market
`matchMarket` was having issues due to async find function.
Changed to flatten out the data before the find.
Also, created links for assets.
> fixes market display bug on property page

- package.json
- yarn.lock
Update @devprotocol/dev-kit to 6.0.5
Updates @devprotocol/dev-kit to 6.0.5
> updates dev-kit to latest

- yarn.lock
Trying to resolve very strange behavior local bugs.
Running `yarn` in main updated the yarn.lock`
> yarn lock update

- src/index.css
> adds syne back in

- src/pages/tokenize-form/DiscordForm.tsx
updates text in Discord Form from 'Channel ID' to 'Server ID'
> updates channel id to server id

- src/pages/network-select/index.tsx
> Add information to the root page

- src/pages/network-select/index.tsx
> Aggre patch 3

- src/pages/properties/ProperySummary/index.tsx
- yarn.lock
Bugfix for #153 
Adds Discord section in Property Overview header
closes #153
> adds discord property details

- src/App.tsx
- src/pages/how-it-works/index.tsx
- src/pages/network-select/index.tsx
> Aggre patch 4

- index.html
meta og:image not working, needs to be fixed
point to github repo image source instead of app img folder
> updates og image to github src

- src/App.tsx
- src/const/cache-path.ts
- src/pages/errors/404.tsx
- src/pages/properties/ProperySummary/index.tsx
- src/pages/properties/property-stakers/index.tsx
- src/pages/properties/property-stakers/useSTokensPositionsOfProperty.ts
- src/utils/utils.ts
Add Property Stakers List
- Adds tab on Property page for stakers
- Creates `useSTokensPositionsOfProperty` hook
- Lists out stakers in cards
- Cleans up 404
> adds stakers list

- src/components/ProgressStepper/ProgressStep.tsx
- src/components/ProgressStepper/ProgressStepper.scss
- src/components/ProgressStepper/index.tsx
- src/const/index.ts
- src/pages/tokenize-form/index.tsx
- src/pages/tokenize-market-select/index.tsx
- src/pages/tokenize-submit/index.tsx
Add Progress Stepper for Tokenize flow
Creates a new Progress stepper
closes #174
> adds progress stepper

- src/components/CopyButton/index.tsx
- src/pages/properties/ProperySummary/index.tsx
- src/pages/user-positions-list/index.tsx
- src/pages/user-properties-list/index.tsx
Adds a simple copy button and implements it for User Address + Property Address
> adds copy to clipboard button

- src/pages/tokenize-submit/TokenizeResult.tsx
- src/pages/tokenize-submit/index.tsx
Prompt the user to add token to metamask wallet list on successful tokenization.
Uses https://eips.ethereum.org/EIPS/eip-747 to prompt wallet to add token to list in TokenizeResult.
closes #227
> Add to wallet list flow

- src/pages/properties/property-stakers/index.tsx
Add placeholder area on Property -> Stakers page when Property Stakers list is empty
Adds placeholder for empty list
closes #232
> adds placeholder when no users staked on property

- src/pages/auth-callback/DiscordAuthCallback.tsx
- src/pages/auth-callback/YouTubeAuthCallback.tsx
- src/pages/tokenize-form/DiscordForm.tsx
- src/pages/tokenize-form/GithubForm.tsx
- src/pages/tokenize-form/YouTubeForm.tsx
- src/pages/tokenize-form/index.tsx
- src/pages/tokenize-submit/index.tsx
- src/utils/utils.ts
Add Popup support for when launching from clubs.
On tokenize, will postMessage to opener and close window if in popup mode.
Updates to tokenize components to check for query params `popup=true`
> handles if launched as popup

- src/pages/auth-callback/DiscordAuthCallback.tsx
- src/pages/tokenize-form/DiscordForm.tsx
Adds popup support for discord auth callback
> adds popup support to discord callback

- src/pages/auth-callback/YouTubeAuthCallback.tsx
- src/pages/tokenize-form/YouTubeForm.tsx
supports youtube auth callback with popup
> support youtube auth callback with popup

- src/pages/tokenize-submit/index.tsx
> add target origin to postMessage

- src/pages/tokenize-form/index.tsx
Temporarily block minting new tokens until KYC is implemented
Redirects to KYC Airtable form.
> redirects to kyc airtable form

- src/pages/tokenize-form/index.tsx
Allow minting through link
Adds allowsAccess query param to tokenize page
> allows access via query params

- src/pages/auth-callback/DiscordAuthCallback.tsx
- src/pages/auth-callback/YouTubeAuthCallback.tsx
- `new URL('/x')` -> `new URL('/x', location.origin)`
> Add missing args to URL constructor

- src/pages/tokenize-form/index.tsx
> removes kyc redirect

- src/pages/auth-callback/DiscordAuthCallback.tsx
- src/pages/auth-callback/YouTubeAuthCallback.tsx
- src/pages/tokenize-form/DiscordForm.tsx
- src/pages/tokenize-form/YouTubeForm.tsx
- src/pages/tokenize-form/index.tsx
- src/types/TokenizeWindowState.ts
Remove unnecessary check for allowAccess in url which was previously used to prevent tokenization
> removes allowAccess for restricting tokenization
